language: java
install: true

sudo: false
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

before_install:
  - chmod +x gradlew

stages:
  - name: build

jobs:
  include:
    - stage: build
      script: ./gradlew build

before_deploy: ./gradlew javadoc

deploy:
  - provider: pages
    local-dir: build/docs/javadoc
    github-token: $GITHUB_TOKEN
    skip-cleanup: true
    keep-history: true
    on:
      branch: master
      jdk: openjdk8
  - provider: script
    script: ./gradlew bintrayUpload -x test -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER
    on:
        tags: true
        jdk: openjdk8
      
